[package]
name = "macros"
version = "0.1.0"
authors = ["Volodymyr Mihdal <volodymyr.migdal@gmail.com>"]
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
ctx = { path = "../ctx" }
syn = { version = "2.0.101", features = ["full"] }
